### ISSUE TITLE
prepend is unsound

### ISSUE THREAD

**Issue by danielhenrymantilla** [abonander/safemem#7]
The current code calls `Vec::set_len()` right after a `Vec::reserve()`, but the reserved bytes have not been initialized in the meantime.

This means that as soon as the `Vec` dereferences to a slice, it instantly triggers Undefined Behavior, since Rust references assert the validity of the stuff they point to.

A way to "prove" this is to explicitly read the input slice in the `copy_over` function, and then run a miri test:

  - [Minimal playground repro, to be run with Miri](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=74e34f28706bbddf6d50158b89a43c20)

**Comment by CAD97** [comment]
It would be good practice to [file an advisory](https://github.com/RustSec/advisory-db/blob/master/CONTRIBUTING.md) for this issue.

(A quick search didn't find one, but if you already have, feel free to ignore this reminder.)
